name: release

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        VER: [1.21.3, 1.21, 1.20.6, 1.20.3]
    steps:
      - uses: actions/checkout@v4
      - env:
          BUILD_VERSION: ${{ matrix.VER }}
        run: |
          sudo chmod 777 ${{github.workspace}}/build.sh
          sudo bash -c ${{github.workspace}}/build.sh

      - name: Upload Artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{github.workspace}}/spigot.jar
          asset_name: spigot-${{ matrix.VER }}.jar
          tag: "main"
          overwrite: true
          release_name: "Prebuilt Spigot server executable"
          body: "Prebuilt Spigot server executable"